const ONLINE_CONVERSATIONS_ACTION_TYPES = {
    SET_ONLINE_CONVERSATIONS: "onlineConverations/SET_ONLINE_CONVERSATIONS",
    SWAP_CONVERSATION_TO_ONLINE: "onlineConverations/SWAP_CONVERSATION_TO_ONLINE",
    SWAP_CONVERSATION_TO_OFFLINE: "onlineConverations/SWAP_CONVERSATION_TO_OFFLINE",
    ADD_MESSAGE_TO_CONVERSATION: "onlineConverations/ADD_MESSAGE_TO_CONVERSATION"
}

export default ONLINE_CONVERSATIONS_ACTION_TYPES;